# Generated by Django 5.1.2 on 2025-06-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='branch_id',
            field=models.IntegerField(blank=True, null=True, default=0),
        ),
    ]
